---
- hosts: '!server*'
  tasks:

    - name: Clear out all config
      nclu:
         commands: del all

    - name: Wipe out quagga log
      shell: echo "" > /etc/quagga/Quagga.conf

- hosts: 'server*'
  vars_files:
    - properties.yml
  any_errors_fatal: true
  tasks:
    - name: Clean out /etc/network/interfaces file
      shell: echo "" > /etc/network/interfaces

    - name: Add basic /etc/network/interfaces file
      blockinfile:
        dest: /etc/network/interfaces
        block: |
          # The loopback network interface
          auto lo
          iface lo inet loopback

          # The primary network interface
          auto eth0
          iface eth0 inet dhcp

    - name: Reload interfaces
      command: /usr/bin/systemd-run --on-active=10 /bin/systemctl reboot
      async: 0
      poll: 0

